### ISSUE TITLE
Exception when building restrictionless entry in database

### ISSUE THREAD

**Issue by MSDandrea** [stone-payments/StrangerData#45]
I'm having a problem with the CreateOne method when i don't use the ::WithValue method, it seems to be when the factory is creating the dictionary of values to be inserted, i get the following exception:

"'minValue' cannot be greater than maxValue.
  Parameter name: minValue"

the code is reached using this code

```csharp
private readonly DataFactory<SqlServerDialect> _dataFactory = new DataFactory<SqlServerDialect>(
            ConfigurationManager
                .ConnectionStrings["Database"]
                .ConnectionString);
.
.
.
  var paymentOrder = _dataFactory.CreateOne("pb.PaymentOrder");
```

StackTrace:
"   at System.Random.Next(Int32 minValue, Int32 maxValue)
   at StrangerData.Any.Long(Int64 minValue, Int64 maxValue)
   at StrangerData.Utils.RandomValues.ForColumn(TableColumnInfo columnInfo)
   at StrangerData.Generator.TableGenerator.GenerateValues()
   at StrangerData.DataFactory`1.CreateOne(String tableName)
   at BalancePaymentOrderReferenceRepositoryIntegrationTests.cs:line 40"

**Comment by rengenesio** [comment]
@MSDandrea can you post the table creation script or the `sp_help 'pb.PaymentOrder'` output?

It seems to be a StrangerData bug when generating random values for 64-bit integer columns (e.g: SQL Server BIGINT) reported on #52
